version: "3.i"

services:
  database:
    container_name: postgres_database
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: questions_db
    volumes:
      - db_vol:/var/lib/postgresql/data
  application:
    container_name: web_application
    build: ./Test_task
    ports:
      - 5000:5000
    command: bash -c "python ./server/application/main.py"
    depends_on:
      - database
volumes:
  db_vol: